name: Update Falco rules in Sysdig

on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - '**.md'

env:
  API_ENDPOINT: app.au1.sysdig.com
  SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Falco Rules
        run: bash update_falco_rules_local.sh
