name: 'API - Update Sysdig Rules'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
        - api_method/**

env:
  API_ENDPOINT: app.au1.sysdig.com
  SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Falco Rules
        working-directory: ./api_method
        run: |
          pip3 install requests
          python3 update_falco_rules.py
